### ISSUE TITLE
Is this module deprecated?

### ISSUE THREAD

**Issue by mariotaku** [FasterXML/jackson-jr-trees#1]
Hello, I found this module is useful for my case, databind is too heavy for me and this module is ok. Is this module deprecated?

**Comment by cowtowncoder** [comment]
No, but it has not yet been implemented. So if anyone is interested in implementing a simple(r) tree model to use with `jackson-jr` (and not having dependency to `jackson-databind`), we are open for contributions.

**Comment by mariotaku** [comment]
I'm closing this because of #2 :)
